### ISSUE TITLE
Build doesn't work locally with recent node/npm versions

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#231]
The build doesn't appear to work with recent node/npm versions. With node v7.10.0 and npm v4.5.0, I get the dreaded `Error: Cannot find module 'internal/fs'`. I think I've traced this down to gitbook 2.6.7 which seems to rely on older versions of node and graceful-fs. On the other hand upgrading gitbook to 3 breaks restructure-navigation which seems to be fixed to gitbook 2.x (upgrading all other dependencies to their latest seems to be ok, including grunt). I also  tried the restructure-navigation3 version in npm and had no luck. It looks like [restructure-navigation](https://github.com/zalando-incubator/gitbook-restructure-navigation) is something Zalando built for itself (and perhaps for these guidelines, not sure). I haven't tried a workaround with moving the global npm/node versions back yet, but that's suboptimal for contributors.

This isn't breaking builds for publishing, but gitbook 3's been out for a while and staying on old versions in the node/npm ecosystem is usually unwise.

**Comment by fmueller** [comment]
We once decided to stick with old Gitbook version https://github.com/zalando/restful-api-guidelines/issues/106

I think, if the guild decides to go with Gitbook 3 the guidelines need to be reordered to fit in default gitbook chapter structure. I would not adapt custom plugins or implement another plugin. Just stick to the default.

**Comment by fmueller** [comment]
And current build is working with Node 5.1.1 Can we at least hardwire this somewhere?

**Comment by dehora** [comment]
> We once decided to stick with old Gitbook version #106

Got it. I don't know how that stays realistic for (#106 is nearly a year old) in this particular ecosystem. It's disappointing the piece holding back an upgrade is an unmaintained Zalando plugin.

**Comment by maxim-tschumak** [comment]
@fmueller We can specify the [engine version](https://docs.npmjs.com/files/package.json#engines) to the package.json.

**Comment by ePaul** [comment]
**From the meeting:** We should mention our decision to stay at this old Gitbook version in BUILD.md (maybe inviting volunteers to work on improving this). @fmueller could you do this?

**Comment by fmueller** [comment]
Yes @ePaul, will put this into BUILD.md and mention it in README accordingly. Good idea.
